# Generated by Django 2.1.4 on 2019-10-14 14:23

from django.db import migrations, models
import django.db.models.deletion
import mailsystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLogRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[(mailsystem.models.RecipientTypeChoices('to'), 'to'), (mailsystem.models.RecipientTypeChoices('cc'), 'cc'), (mailsystem.models.RecipientTypeChoices('bcc'), 'bcc')], max_length=3)),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='maillogsession',
            name='recipient_email',
        ),
        migrations.AlterField(
            model_name='maillogsession',
            name='context',
            field=models.TextField(help_text='Context, used for E-Mail rendering'),
        ),
        migrations.AlterField(
            model_name='maillogsession',
            name='email',
            field=models.TextField(help_text='Full E-Mail'),
        ),
        migrations.AlterField(
            model_name='maillogsession',
            name='send_at',
            field=models.DateTimeField(auto_now=True, help_text='Send Timestamp'),
        ),
        migrations.AlterField(
            model_name='maillogsession',
            name='sender_email',
            field=models.EmailField(help_text='E-Mail Sender', max_length=255),
        ),
        migrations.AlterField(
            model_name='maillogsession',
            name='uuid',
            field=models.UUIDField(editable=False, help_text='E-Mail header Identificator'),
        ),
        migrations.AddField(
            model_name='maillogrecipient',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsystem.MailLogSession'),
        ),
    ]
