# Generated by Django 2.1.4 on 2018-12-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('type', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('insert', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('recipient_email', models.EmailField(max_length=255)),
                ('sender_email', models.EmailField(max_length=255)),
                ('context', models.TextField()),
                ('email', models.TextField()),
                ('send_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='maillog',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maillog.MailSession'),
        ),
    ]
